Repository leather-io/extension, pull requests merged in 2023-10, with the labels that each got.

#4208 fix: fix fund page responsiveness, refactor mediaQuery, closes #4188
  src/app/components/account/account-list-item-layout.tsx
  src/app/components/page-title.tsx
  src/app/pages/choose-account/components/accounts.tsx
  src/app/pages/fund/components/fiat-providers-list.tsx
  src/app/pages/fund/fund.layout.tsx
  src/app/pages/home/components/account-info-card.tsx
  src/app/pages/home/components/home.layout.tsx
Labels: 1 Day Dev 🎽

#4354 fix: properly switch between 12 and 24 word inputs
  src/app/pages/onboarding/sign-in/sign-in.tsx
  tests/specs/onboarding/onboarding.spec.ts
Labels: 1 Day Dev 🎽

#4363 fix: align text and caption left so it appears correctly in extension…
  src/app/components/crypto-assets/components/asset-row-grid.tsx
Labels: Visual bug 🧼

#4132 feat: added Bitcoin Contracts entry point and list page
  src/app/common/hooks/use-bitcoin-contracts.ts
  src/app/common/utils.ts
  src/app/components/bitcoin-contract-entry-point/bitcoin-contract-entry-point-layout.tsx
  src/app/components/bitcoin-contract-entry-point/bitcoin-contract-entry-point.tsx
  src/app/components/icons/bitcoin-contract-icon.tsx
  src/app/components/loading-spinner.tsx
  src/app/features/asset-list/asset-list.tsx
  src/app/pages/bitcoin-contract-list/bitcoin-contract-list.tsx
  src/app/pages/bitcoin-contract-list/components/bitcoin-contract-list-item-layout.tsx
  src/app/pages/bitcoin-contract-list/components/bitcoin-contract-list-layout.tsx
  src/app/pages/bitcoin-contract-request/bitcoin-contract-request.tsx
  src/app/query/bitcoin/contract/check-dlc-link-attestor-health.ts
  src/app/routes/app-routes.tsx
Labels: Enhancement 💡, P2 Enhancement ⚡️, DLC

#4390 chore: import prettier config from monorepo, closes #4268
  .prettierrc.js
  package.json
  yarn.lock
Labels: 💊 Code health, Developers ⚙️, DevOps 🧑‍💻
